spring.application.name=demo

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/java
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración para subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=./uploads

# Configuraciones JWT
jwt.secret=tuClaveSecretaMuyLargaYCompleja
jwt.expiration=3600


# Configuración de logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.security=DEBUG

# Configuración de archivo de log (opcional)
logging.file.name=logs/application.log

# Asegurar que el compilador retenga los nombres de parámetros
spring.mvc.throw-exception-if-no-handler-found=true


